name: 'audit_helper'
version: '0.4.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
