{{ 
    audit_helper.reworked_compare(
        ref('unit_test_model_a'),
        ref('unit_test_model_b'),
        primary_key='id',
        columns=var('reworked_compare__columns'),
        event_time=var('reworked_compare__event_time')
    ) 
}}