name: 'audit_helper_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

seeds:
  +quote_columns: false

vars:
  compare_queries_summarize: true
  reworked_compare__primary_key_columns: ['col1']
  reworked_compare__columns: ['col1']
  reworked_compare__event_time:
  quick_are_queries_identical_cols: ['col1']
  quick_are_queries_identical_event_time:

flags:
  send_anonymous_usage_stats: False
  use_colors: True