version: 2

models:
  - name: compare_queries
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relations_without_exclude')
          
  - name: compare_queries_with_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_with_summary')

  - name: compare_queries_without_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_without_summary')
          
  - name: compare_relations_with_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_with_summary')

  - name: compare_relations_without_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_without_summary')

  - name: compare_relations_with_exclude
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relations_with_exclude')

  - name: compare_relations_without_exclude
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relations_without_exclude')

  - name: compare_all_columns_with_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_all_columns_with_summary')

  - name: compare_all_columns_without_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_all_columns_without_summary')
  

  - name: compare_all_columns_with_summary_and_exclude
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_all_columns_with_summary_and_exclude')
  
  - name: compare_all_columns_where_clause
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_all_columns_where_clause')

  - name: compare_relation_columns
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relation_columns')

  - name: report_compare_all_columns
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_all_columns')

  - name: report_compare_relation_columns
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_relation_columns')

  - name: report_compare_relations_with_exclude
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_relations')

  - name: report_compare_relations_without_identifiers
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_relations_without_identifiers')

  - name: report_compare_relations
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_relations')

  - name: report_folder_compare_all_columns
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_all_columns')

  - name: report_folder_compare_relation_columns
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_relation_columns')

  - name: report_folder_compare_relations
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__report_compare_relations')